const translations = {
    en: {
        // Header
        'nav.menu':      'MENU',
        'nav.home':      'HOME',
        'nav.contact':   'CONTACT',
        'nav.products':  'PRODUCTS',
        'nav.subscribe': 'SUBSCRIBE',

        // Footer
        'ft.nav':        'Navigation',
        'ft.cats':       'Categories',
        'ft.contact':    'Contact',
        'ft.gaming':     'Gaming PCs',
        'ft.components': 'Components',
        'ft.peripherals':'Peripherals',
        'ft.refurb':     'Refurbished',
        'ft.send':       'Send a message',
        'ft.hours':      'Mon – Fri, 9am – 6pm',
        'ft.copy':       '© 2026 FINSTATECH. All rights reserved.',
        'ft.built':      'Built with passion for tech.',

        // Index — Top Picks
        'top.picks':  'Top Picks',
        'top.ram.h':  'High-Speed DDR5 RAM',
        'top.ram.p':  'Unlock next-gen performance for your rig.',
        'top.ssd.h':  'Gen4 NVMe SSD',
        'top.ssd.p':  'Experience lightning-fast load times.',
        'top.kb.h':   'RGB Mechanical Keyboard',
        'top.kb.p':   'Clicky, responsive, and fully customizable.',

        // Index — Refurbished Deals
        'ref.eyebrow':  'CERTIFIED REFURBISHED',
        'ref.title':    'Refurbished <span>Deals</span>',
        'ref.sub':      'Half the price. Same performance. Refurbished & verified.',
        'ref.badge':    '50% OFF',
        'ref.mx3s.p':   'Wireless mouse, refurbished. Works on any surface.',
        'ref.mxk.p':    'Full-size wireless keyboard. Quiet and backlit.',
        'ref.cam.p':    '1080p 60fps webcam. USB-C, great for WFH or streaming.',
        'ref.zone.p':   'Office headset with noise-cancelling mic. All-day comfort.',
        'ref.mxa.p':    'Compact travel mouse. Works on any surface, even glass.',
        'ref.mxkm.p':   'Compact wireless keyboard. Quiet, backlit, portable.',

        // Productos
        'prod.gaming':       '<span>Gaming</span> PCs',
        'prod.performance':  '<span>Performance</span> Components',
        'prod.essential':    '<span>Essential</span> Peripherals',
        'prod.view':         'View Details',
        'prod.ryzen.p':      'The king of gaming CPUs.',
        'prod.rtx.p':        'Great value 1080p/1440p gaming.',
        'prod.crucial.p':    'Blazing fast Gen4 NVMe storage.',
        'prod.gskill.p':     '6000MHz CL30 DDR5 for optimal performance.',
        'prod.glide.p':      'Lightweight, ergonomic, and precise.',
        'prod.pad.p':        'XL mousepad for maximum coverage.',
        'prod.sound.p':      'Clear audio for immersive gaming.',
        'prod.keycaps.p':    'PBT double-shot keycaps for durability.',

        // Producto (detail page)
        'pd.back':       '← Back to products',
        'pd.addcart':    'Add to Cart',
        'pd.buy':        'Buy Now',
        'pd.notify':     '✓ We\'ll notify you when available',
        'pd.share':      'Share',
        'pd.specs':      'Specifications',
        'pd.related':    'You might also like',

        // Cart
        'cart.title':    'Your Cart',
        'cart.empty':    'Your cart is empty.',
        'cart.browse':   'Browse products →',
        'cart.remove':   'Remove',
        'cart.subtotal': 'Subtotal',
        'cart.shipping': 'Shipping',
        'cart.free':     'Free',
        'cart.total':    'Total',
        'cart.checkout': 'Proceed to Checkout',
        'cart.added':    '✓ Added to cart',
        'cart.demo':     'This is a demo store. No real purchases will be made.',

        // Contacto
        'ct.eyebrow':    "WE'RE HERE",
        'ct.title':      'Talk to <span>us</span>',
        'ct.desc':       "Have a question about an order, a product, or just want to say hi? Write to us and we'll get back to you soon.",
        'ct.email.lbl':  'Email',
        'ct.hours.lbl':  'Hours',
        'ct.hours.val':  'Mon – Fri, 9am – 6pm',
        'ct.name.ph':    'Your name',
        'ct.email.ph':   'Your email address',
        'ct.subject.ph': 'Subject',
        'ct.msg.ph':     'Your message...',
        'ct.send':       'SEND MESSAGE',

        // Suscribirte
        'sub.eyebrow':      'FREE MEMBERSHIP',
        'sub.hero.title':   'Exclusive <span>access</span>.<br>Before anyone else.',
        'sub.hero.desc':    "Be the first to know about drops, refurbished deals, and launches. The tech community that won't spam you.",
        'sub.perks.title':  'What do you get?',
        'sub.p1.h':         'Exclusive Deals',
        'sub.p1.p':         'Early access to new and refurbished product deals before they go live.',
        'sub.p2.h':         'Guides & Reviews',
        'sub.p2.p':         'Technical content without filler — comparisons, recommended builds and more.',
        'sub.p3.h':         'Refurbished Drops',
        'sub.p3.p':         'We notify you when refurbished stock arrives before it sells out.',
        'sub.p4.h':         'No spam. Ever.',
        'sub.p4.p':         'Only emails worth reading. Cancel anytime, no drama.',
        'sub.form.title':   'Join now',
        'sub.form.sub':     "It's free. It always will be.",
        'sub.name.ph':      'Your name',
        'sub.email.ph':     'Your email address',
        'sub.chk1':         'Deals & offers',
        'sub.chk2':         'New articles',
        'sub.chk3':         'Refurbished drops',
        'sub.btn':          'SUBSCRIBE NOW',
        'sub.disclaimer':   'By subscribing you agree to receive emails from FINSTATECH. You can unsubscribe at any time.',
        'sub.stat1':        'active subscribers',
        'sub.stat2':        'emails per week',
        'sub.stat3':        'spam. guaranteed.',
        'sub.success':      '✓ SUBSCRIBED',
    },

    fr: {
        'nav.menu':      'MENU',
        'nav.home':      'ACCUEIL',
        'nav.contact':   'CONTACT',
        'nav.products':  'PRODUITS',
        'nav.subscribe': "S'ABONNER",

        'ft.nav':        'Navigation',
        'ft.cats':       'Catégories',
        'ft.contact':    'Contact',
        'ft.gaming':     'PC Gaming',
        'ft.components': 'Composants',
        'ft.peripherals':'Périphériques',
        'ft.refurb':     'Reconditionné',
        'ft.send':       'Envoyer un message',
        'ft.hours':      'Lun – Ven, 9h – 18h',
        'ft.copy':       '© 2026 FINSTATECH. Tous droits réservés.',
        'ft.built':      'Fait avec passion pour la tech.',

        'top.picks':  'Sélection',
        'top.ram.h':  'RAM DDR5 Haute Vitesse',
        'top.ram.p':  'Libérez les performances de nouvelle génération.',
        'top.ssd.h':  'SSD NVMe Gen4',
        'top.ssd.p':  'Des temps de chargement ultra-rapides.',
        'top.kb.h':   'Clavier Mécanique RGB',
        'top.kb.p':   'Cliquetant, réactif et entièrement personnalisable.',

        'ref.eyebrow':  'RECONDITIONNÉ CERTIFIÉ',
        'ref.title':    'Offres <span>Reconditionnées</span>',
        'ref.sub':      'Moitié prix. Mêmes performances. Reconditionné & vérifié.',
        'ref.badge':    '50% DE RÉDUCTION',
        'ref.mx3s.p':   'Souris sans fil reconditionnée. Fonctionne sur toutes les surfaces.',
        'ref.mxk.p':    'Clavier sans fil pleine taille. Silencieux et rétroéclairé.',
        'ref.cam.p':    'Webcam 1080p 60fps. USB-C, idéale pour télétravail ou streaming.',
        'ref.zone.p':   'Casque bureau avec micro antibruit. Confort toute la journée.',
        'ref.mxa.p':    'Souris compacte de voyage. Fonctionne sur toutes surfaces, même le verre.',
        'ref.mxkm.p':   'Clavier sans fil compact. Silencieux, rétroéclairé et portable.',

        'prod.gaming':       '<span>Gaming</span> PCs',
        'prod.performance':  'Composants <span>Performance</span>',
        'prod.essential':    'Périphériques <span>Essentiels</span>',
        'prod.view':         'Voir Détails',
        'prod.ryzen.p':      'Le roi des CPU gaming.',
        'prod.rtx.p':        'Excellent rapport qualité-prix en 1080p/1440p.',
        'prod.crucial.p':    'Stockage Gen4 NVMe ultra-rapide.',
        'prod.gskill.p':     '6000MHz CL30 DDR5 pour des performances optimales.',
        'prod.glide.p':      'Légère, ergonomique et précise.',
        'prod.pad.p':        'Tapis de souris XL pour une couverture maximale.',
        'prod.sound.p':      'Audio clair pour un gaming immersif.',
        'prod.keycaps.p':    'Touches PBT double injection pour la durabilité.',

        'pd.back':       '← Retour aux produits',
        'pd.addcart':    'Ajouter au panier',
        'pd.buy':        'Acheter maintenant',
        'pd.notify':     '✓ Nous vous préviendrons quand disponible',
        'pd.share':      'Partager',
        'pd.specs':      'Spécifications',
        'pd.related':    'Vous aimerez aussi',

        'cart.title':    'Votre Panier',
        'cart.empty':    'Votre panier est vide.',
        'cart.browse':   'Voir les produits →',
        'cart.remove':   'Supprimer',
        'cart.subtotal': 'Sous-total',
        'cart.shipping': 'Livraison',
        'cart.free':     'Gratuite',
        'cart.total':    'Total',
        'cart.checkout': 'Passer à la caisse',
        'cart.added':    '✓ Ajouté au panier',
        'cart.demo':     'Ceci est une boutique démo. Aucun achat réel ne sera effectué.',

        'ct.eyebrow':    'NOUS SOMMES LÀ',
        'ct.title':      'Parlez-nous <span>maintenant</span>',
        'ct.desc':       'Vous avez une question sur une commande, un produit ou juste envie de dire bonjour ? Écrivez-nous et nous répondrons rapidement.',
        'ct.email.lbl':  'Email',
        'ct.hours.lbl':  'Horaires',
        'ct.hours.val':  'Lun – Ven, 9h – 18h',
        'ct.name.ph':    'Votre nom',
        'ct.email.ph':   'Votre adresse email',
        'ct.subject.ph': 'Sujet',
        'ct.msg.ph':     'Votre message...',
        'ct.send':       'ENVOYER LE MESSAGE',

        'sub.eyebrow':      'ABONNEMENT GRATUIT',
        'sub.hero.title':   'Accès <span>exclusif</span>.<br>Avant tout le monde.',
        'sub.hero.desc':    "Soyez le premier informé des drops, offres reconditionnées et lancements. La communauté tech sans spam.",
        'sub.perks.title':  'Que recevez-vous ?',
        'sub.p1.h':         'Offres Exclusives',
        'sub.p1.p':         "Accès anticipé aux offres de produits neufs et reconditionnés avant leur mise en ligne.",
        'sub.p2.h':         'Guides & Avis',
        'sub.p2.p':         'Contenu technique sans remplissage — comparaisons, builds recommandés et plus.',
        'sub.p3.h':         'Drops Reconditionnés',
        'sub.p3.p':         'Nous vous avertissons quand du stock reconditionné arrive avant épuisement.',
        'sub.p4.h':         'Zéro spam. Jamais.',
        'sub.p4.p':         "Uniquement des emails qui valent la peine. Annulez quand vous voulez, sans drama.",
        'sub.form.title':   'Rejoindre maintenant',
        'sub.form.sub':     "C'est gratuit. Ça le sera toujours.",
        'sub.name.ph':      'Votre nom',
        'sub.email.ph':     'Votre adresse email',
        'sub.chk1':         'Offres & promotions',
        'sub.chk2':         'Nouveaux articles',
        'sub.chk3':         'Drops reconditionnés',
        'sub.btn':          "S'ABONNER MAINTENANT",
        'sub.disclaimer':   "En vous abonnant vous acceptez de recevoir des emails de FINSTATECH. Vous pouvez vous désabonner à tout moment.",
        'sub.stat1':        'abonnés actifs',
        'sub.stat2':        'emails par semaine',
        'sub.stat3':        'spam. garanti.',
        'sub.success':      '✓ ABONNÉ',
    },

    es: {
        'nav.menu':      'MENÚ',
        'nav.home':      'INICIO',
        'nav.contact':   'CONTACTO',
        'nav.products':  'ARTÍCULOS',
        'nav.subscribe': 'SUSCRÍBETE',

        'ft.nav':        'Navegación',
        'ft.cats':       'Categorías',
        'ft.contact':    'Contacto',
        'ft.gaming':     'PCs Gaming',
        'ft.components': 'Componentes',
        'ft.peripherals':'Periféricos',
        'ft.refurb':     'Reacondicionado',
        'ft.send':       'Enviar un mensaje',
        'ft.hours':      'Lun – Vie, 9am – 6pm',
        'ft.copy':       '© 2026 FINSTATECH. Todos los derechos reservados.',
        'ft.built':      'Hecho con pasión por la tecnología.',

        'top.picks':  'Top Picks',
        'top.ram.h':  'RAM DDR5 de Alta Velocidad',
        'top.ram.p':  'Desbloquea el rendimiento de próxima generación.',
        'top.ssd.h':  'SSD NVMe Gen4',
        'top.ssd.p':  'Tiempos de carga ultrarrápidos.',
        'top.kb.h':   'Teclado Mecánico RGB',
        'top.kb.p':   'Con clicks, responsivo y totalmente personalizable.',

        'ref.eyebrow':  'CERTIFICADO REACONDICIONADO',
        'ref.title':    'Ofertas <span>Reacondicionadas</span>',
        'ref.sub':      'La mitad del precio. El mismo rendimiento. Reacondicionado y verificado.',
        'ref.badge':    '50% OFF',
        'ref.mx3s.p':   'Ratón inalámbrico reacondicionado. Funciona en cualquier superficie.',
        'ref.mxk.p':    'Teclado inalámbrico completo. Silencioso e iluminado.',
        'ref.cam.p':    'Webcam 1080p 60fps. USB-C, ideal para trabajo remoto o streaming.',
        'ref.zone.p':   'Auriculares de oficina con micrófono cancelador de ruido.',
        'ref.mxa.p':    'Ratón compacto de viaje. Funciona en cualquier superficie, incluso vidrio.',
        'ref.mxkm.p':   'Teclado inalámbrico compacto. Silencioso, iluminado y portátil.',

        'prod.gaming':       '<span>Gaming</span> PCs',
        'prod.performance':  '<span>Rendimiento</span> Componentes',
        'prod.essential':    '<span>Periféricos</span> Esenciales',
        'prod.view':         'Ver Detalles',
        'prod.ryzen.p':      'El rey de las CPUs para gaming.',
        'prod.rtx.p':        'Gran valor para gaming en 1080p/1440p.',
        'prod.crucial.p':    'Almacenamiento Gen4 NVMe ultrarrápido.',
        'prod.gskill.p':     '6000MHz CL30 DDR5 para rendimiento óptimo.',
        'prod.glide.p':      'Ligero, ergonómico y preciso.',
        'prod.pad.p':        'Mousepad XL para máxima cobertura.',
        'prod.sound.p':      'Audio claro para gaming inmersivo.',
        'prod.keycaps.p':    'Teclas PBT doble inyección para durabilidad.',

        'pd.back':       '← Volver a productos',
        'pd.addcart':    'Añadir al carrito',
        'pd.buy':        'Comprar ahora',
        'pd.notify':     '✓ Te avisaremos cuando esté disponible',
        'pd.share':      'Compartir',
        'pd.specs':      'Especificaciones',
        'pd.related':    'También te puede gustar',

        'cart.title':    'Tu Carrito',
        'cart.empty':    'Tu carrito está vacío.',
        'cart.browse':   'Ver productos →',
        'cart.remove':   'Eliminar',
        'cart.subtotal': 'Subtotal',
        'cart.shipping': 'Envío',
        'cart.free':     'Gratis',
        'cart.total':    'Total',
        'cart.checkout': 'Ir al pago',
        'cart.added':    '✓ Añadido al carrito',
        'cart.demo':     'Esta es una tienda demo. No se realizarán compras reales.',

        'ct.eyebrow':    'ESTAMOS AQUÍ',
        'ct.title':      'Habla con <span>nosotros</span>',
        'ct.desc':       '¿Tienes una pregunta sobre un pedido, un producto o simplemente quieres saludar? Escríbenos y te respondemos pronto.',
        'ct.email.lbl':  'Email',
        'ct.hours.lbl':  'Horario',
        'ct.hours.val':  'Lun – Vie, 9am – 6pm',
        'ct.name.ph':    'Tu nombre',
        'ct.email.ph':   'Tu correo electrónico',
        'ct.subject.ph': 'Asunto',
        'ct.msg.ph':     'Tu mensaje...',
        'ct.send':       'ENVIAR MENSAJE',

        'sub.eyebrow':      'MEMBRESÍA GRATUITA',
        'sub.hero.title':   'Acceso <span>exclusivo</span>.<br>Antes que nadie.',
        'sub.hero.desc':    'Sé el primero en enterarte de drops, ofertas reacondicionadas, y lanzamientos. La comunidad tech que no te va a spamear.',
        'sub.perks.title':  '¿Qué obtienes?',
        'sub.p1.h':         'Deals exclusivos',
        'sub.p1.p':         'Acceso anticipado a ofertas de productos nuevos y reacondicionados antes de que se publiquen.',
        'sub.p2.h':         'Guías y reviews',
        'sub.p2.p':         'Contenido técnico sin relleno — comparativas, builds recomendados y más.',
        'sub.p3.h':         'Drops refurbished',
        'sub.p3.p':         'Te avisamos cuando llega stock reacondicionado antes de que se agote.',
        'sub.p4.h':         'Sin spam. Nunca.',
        'sub.p4.p':         'Solo correos que valen la pena. Cancela cuando quieras, sin drama.',
        'sub.form.title':   'Únete ahora',
        'sub.form.sub':     'Es gratis. Siempre lo será.',
        'sub.name.ph':      'Tu nombre',
        'sub.email.ph':     'Tu correo electrónico',
        'sub.chk1':         'Deals y ofertas',
        'sub.chk2':         'Nuevos artículos',
        'sub.chk3':         'Refurbished drops',
        'sub.btn':          'SUSCRIBIRME AHORA',
        'sub.disclaimer':   'Al suscribirte aceptas recibir correos de FINSTATECH. Puedes darte de baja en cualquier momento.',
        'sub.stat1':        'suscriptores activos',
        'sub.stat2':        'emails por semana',
        'sub.stat3':        'spam. garantizado.',
        'sub.success':      '✓ SUSCRITO',
    },

    de: {
        'nav.menu':      'MENÜ',
        'nav.home':      'START',
        'nav.contact':   'KONTAKT',
        'nav.products':  'ARTIKEL',
        'nav.subscribe': 'ABONNIEREN',

        'ft.nav':        'Navigation',
        'ft.cats':       'Kategorien',
        'ft.contact':    'Kontakt',
        'ft.gaming':     'Gaming PCs',
        'ft.components': 'Komponenten',
        'ft.peripherals':'Peripheriegeräte',
        'ft.refurb':     'Generalüberholt',
        'ft.send':       'Nachricht senden',
        'ft.hours':      'Mo – Fr, 9:00 – 18:00 Uhr',
        'ft.copy':       '© 2026 FINSTATECH. Alle Rechte vorbehalten.',
        'ft.built':      'Mit Leidenschaft für Tech gebaut.',

        'top.picks':  'Top Picks',
        'top.ram.h':  'Hochgeschwindigkeits DDR5 RAM',
        'top.ram.p':  'Entfessle die nächste Generation deines Rigs.',
        'top.ssd.h':  'Gen4 NVMe SSD',
        'top.ssd.p':  'Erlebe blitzschnelle Ladezeiten.',
        'top.kb.h':   'RGB Mechanische Tastatur',
        'top.kb.p':   'Klickend, reaktionsschnell und vollständig anpassbar.',

        'ref.eyebrow':  'ZERTIFIZIERT GENERALÜBERHOLT',
        'ref.title':    'Generalüberholte <span>Angebote</span>',
        'ref.sub':      'Halber Preis. Gleiche Leistung. Generalüberholt & geprüft.',
        'ref.badge':    '50% RABATT',
        'ref.mx3s.p':   'Kabellose Maus, generalüberholt. Auf jeder Oberfläche einsetzbar.',
        'ref.mxk.p':    'Kabellose Vollformattastatur. Leise und beleuchtet.',
        'ref.cam.p':    '1080p 60fps Webcam. USB-C, ideal für Homeoffice oder Streaming.',
        'ref.zone.p':   'Büro-Headset mit Geräuschunterdrückung. Ganztageskomfort.',
        'ref.mxa.p':    'Kompakte Reisemaus. Funktioniert auf jeder Oberfläche, sogar Glas.',
        'ref.mxkm.p':   'Kompakte kabellose Tastatur. Leise, beleuchtet, portabel.',

        'prod.gaming':       '<span>Gaming</span> PCs',
        'prod.performance':  '<span>Leistungs</span>komponenten',
        'prod.essential':    '<span>Wesentliche</span> Peripheriegeräte',
        'prod.view':         'Details anzeigen',
        'prod.ryzen.p':      'Der König der Gaming-CPUs.',
        'prod.rtx.p':        'Bestes Preis-Leistungs-Verhältnis für 1080p/1440p.',
        'prod.crucial.p':    'Blitzschneller Gen4 NVMe Speicher.',
        'prod.gskill.p':     '6000MHz CL30 DDR5 für optimale Leistung.',
        'prod.glide.p':      'Leicht, ergonomisch und präzise.',
        'prod.pad.p':        'XL Mauspad für maximale Abdeckung.',
        'prod.sound.p':      'Klarer Sound für immersives Gaming.',
        'prod.keycaps.p':    'PBT Doppelschuss-Keycaps für Langlebigkeit.',

        'pd.back':       '← Zurück zu Produkten',
        'pd.addcart':    'In den Warenkorb',
        'pd.buy':        'Jetzt kaufen',
        'pd.notify':     '✓ Wir benachrichtigen dich wenn verfügbar',
        'pd.share':      'Teilen',
        'pd.specs':      'Spezifikationen',
        'pd.related':    'Das könnte dir auch gefallen',

        'cart.title':    'Dein Warenkorb',
        'cart.empty':    'Dein Warenkorb ist leer.',
        'cart.browse':   'Produkte ansehen →',
        'cart.remove':   'Entfernen',
        'cart.subtotal': 'Zwischensumme',
        'cart.shipping': 'Versand',
        'cart.free':     'Kostenlos',
        'cart.total':    'Gesamt',
        'cart.checkout': 'Zur Kasse',
        'cart.added':    '✓ In den Warenkorb gelegt',
        'cart.demo':     'Dies ist ein Demo-Shop. Es werden keine echten Käufe getätigt.',

        'ct.eyebrow':    'WIR SIND HIER',
        'ct.title':      'Sprich mit <span>uns</span>',
        'ct.desc':       'Hast du eine Frage zu einer Bestellung oder einem Produkt? Schreib uns und wir melden uns bald.',
        'ct.email.lbl':  'E-Mail',
        'ct.hours.lbl':  'Öffnungszeiten',
        'ct.hours.val':  'Mo – Fr, 9:00 – 18:00 Uhr',
        'ct.name.ph':    'Dein Name',
        'ct.email.ph':   'Deine E-Mail-Adresse',
        'ct.subject.ph': 'Betreff',
        'ct.msg.ph':     'Deine Nachricht...',
        'ct.send':       'NACHRICHT SENDEN',

        'sub.eyebrow':      'KOSTENLOSE MITGLIEDSCHAFT',
        'sub.hero.title':   'Exklusiver <span>Zugang</span>.<br>Vor allen anderen.',
        'sub.hero.desc':    'Erfahre als Erster von Drops, generalüberholten Angeboten und Neuerscheinungen. Die Tech-Community ohne Spam.',
        'sub.perks.title':  'Was bekommst du?',
        'sub.p1.h':         'Exklusive Deals',
        'sub.p1.p':         'Frühzeitiger Zugang zu neuen und generalüberholten Produktangeboten.',
        'sub.p2.h':         'Guides & Reviews',
        'sub.p2.p':         'Technische Inhalte ohne Füllstoff — Vergleiche, empfohlene Builds und mehr.',
        'sub.p3.h':         'Refurbished Drops',
        'sub.p3.p':         'Wir benachrichtigen dich, wenn generalüberholter Bestand eintrifft.',
        'sub.p4.h':         'Kein Spam. Nie.',
        'sub.p4.p':         'Nur E-Mails, die es wert sind. Jederzeit kündbar, ohne Drama.',
        'sub.form.title':   'Jetzt beitreten',
        'sub.form.sub':     'Es ist kostenlos. Immer.',
        'sub.name.ph':      'Dein Name',
        'sub.email.ph':     'Deine E-Mail-Adresse',
        'sub.chk1':         'Deals & Angebote',
        'sub.chk2':         'Neue Artikel',
        'sub.chk3':         'Refurbished Drops',
        'sub.btn':          'JETZT ABONNIEREN',
        'sub.disclaimer':   'Mit deiner Anmeldung stimmst du zu, E-Mails von FINSTATECH zu erhalten. Du kannst dich jederzeit abmelden.',
        'sub.stat1':        'aktive Abonnenten',
        'sub.stat2':        'E-Mails pro Woche',
        'sub.stat3':        'Spam. garantiert.',
        'sub.success':      '✓ ABONNIERT',
    },

    it: {
        'nav.menu':      'MENU',
        'nav.home':      'INIZIO',
        'nav.contact':   'CONTATTO',
        'nav.products':  'ARTICOLI',
        'nav.subscribe': 'ISCRIVITI',

        'ft.nav':        'Navigazione',
        'ft.cats':       'Categorie',
        'ft.contact':    'Contatto',
        'ft.gaming':     'PC Gaming',
        'ft.components': 'Componenti',
        'ft.peripherals':'Periferiche',
        'ft.refurb':     'Ricondizionato',
        'ft.send':       'Invia un messaggio',
        'ft.hours':      'Lun – Ven, 9:00 – 18:00',
        'ft.copy':       '© 2026 FINSTATECH. Tutti i diritti riservati.',
        'ft.built':      'Fatto con passione per la tech.',

        'top.picks':  'Top Picks',
        'top.ram.h':  'RAM DDR5 ad Alta Velocità',
        'top.ram.p':  'Sblocca le prestazioni di nuova generazione.',
        'top.ssd.h':  'SSD NVMe Gen4',
        'top.ssd.p':  'Tempi di caricamento fulminei.',
        'top.kb.h':   'Tastiera Meccanica RGB',
        'top.kb.p':   'Scattante, reattiva e completamente personalizzabile.',

        'ref.eyebrow':  'RICONDIZIONATO CERTIFICATO',
        'ref.title':    'Offerte <span>Ricondizionate</span>',
        'ref.sub':      'Metà del prezzo. Stesse prestazioni. Ricondizionato e verificato.',
        'ref.badge':    '50% SCONTO',
        'ref.mx3s.p':   'Mouse wireless ricondizionato. Funziona su qualsiasi superficie.',
        'ref.mxk.p':    'Tastiera wireless completa. Silenziosa e retroilluminata.',
        'ref.cam.p':    'Webcam 1080p 60fps. USB-C, ottima per smart working o streaming.',
        'ref.zone.p':   'Cuffie da ufficio con microfono a cancellazione del rumore.',
        'ref.mxa.p':    'Mouse compatto da viaggio. Funziona su qualsiasi superficie, anche vetro.',
        'ref.mxkm.p':   'Tastiera wireless compatta. Silenziosa, retroilluminata e portatile.',

        'prod.gaming':       '<span>Gaming</span> PC',
        'prod.performance':  '<span>Componenti</span> Prestazioni',
        'prod.essential':    '<span>Periferici</span> Essenziali',
        'prod.view':         'Vedi Dettagli',
        'prod.ryzen.p':      'Il re delle CPU per gaming.',
        'prod.rtx.p':        'Ottimo rapporto qualità-prezzo per 1080p/1440p.',
        'prod.crucial.p':    'Archiviazione Gen4 NVMe velocissima.',
        'prod.gskill.p':     '6000MHz CL30 DDR5 per prestazioni ottimali.',
        'prod.glide.p':      'Leggero, ergonomico e preciso.',
        'prod.pad.p':        'Tappetino XL per la massima copertura.',
        'prod.sound.p':      'Audio nitido per un gaming immersivo.',
        'prod.keycaps.p':    'Tasti PBT double-shot per la durabilità.',

        'pd.back':       '← Torna ai prodotti',
        'pd.addcart':    'Aggiungi al carrello',
        'pd.buy':        'Acquista ora',
        'pd.notify':     '✓ Ti avviseremo quando disponibile',
        'pd.share':      'Condividi',
        'pd.specs':      'Specifiche',
        'pd.related':    'Potrebbe piacerti anche',

        'cart.title':    'Il tuo Carrello',
        'cart.empty':    'Il tuo carrello è vuoto.',
        'cart.browse':   'Sfoglia i prodotti →',
        'cart.remove':   'Rimuovi',
        'cart.subtotal': 'Subtotale',
        'cart.shipping': 'Spedizione',
        'cart.free':     'Gratuita',
        'cart.total':    'Totale',
        'cart.checkout': 'Procedi al pagamento',
        'cart.added':    '✓ Aggiunto al carrello',
        'cart.demo':     'Questo è un negozio demo. Non verranno effettuati acquisti reali.',

        'ct.eyebrow':    'SIAMO QUI',
        'ct.title':      'Parla con <span>noi</span>',
        'ct.desc':       'Hai una domanda su un ordine o un prodotto? Scrivici e ti risponderemo presto.',
        'ct.email.lbl':  'Email',
        'ct.hours.lbl':  'Orari',
        'ct.hours.val':  'Lun – Ven, 9:00 – 18:00',
        'ct.name.ph':    'Il tuo nome',
        'ct.email.ph':   'Il tuo indirizzo email',
        'ct.subject.ph': 'Oggetto',
        'ct.msg.ph':     'Il tuo messaggio...',
        'ct.send':       'INVIA MESSAGGIO',

        'sub.eyebrow':      'ISCRIZIONE GRATUITA',
        'sub.hero.title':   'Accesso <span>esclusivo</span>.<br>Prima di tutti.',
        'sub.hero.desc':    'Sii il primo a scoprire drops, offerte ricondizionate e lanci. La community tech senza spam.',
        'sub.perks.title':  'Cosa ottieni?',
        'sub.p1.h':         'Offerte Esclusive',
        'sub.p1.p':         'Accesso anticipato alle offerte di prodotti nuovi e ricondizionati.',
        'sub.p2.h':         'Guide & Recensioni',
        'sub.p2.p':         'Contenuti tecnici senza riempitivi — confronti, build consigliate e altro.',
        'sub.p3.h':         'Drops Ricondizionati',
        'sub.p3.p':         'Ti avvisiamo quando arriva stock ricondizionato prima che si esaurisca.',
        'sub.p4.h':         'Niente spam. Mai.',
        'sub.p4.p':         'Solo email che valgono la pena. Cancella quando vuoi, senza problemi.',
        'sub.form.title':   'Unisciti ora',
        'sub.form.sub':     'È gratuito. Lo sarà sempre.',
        'sub.name.ph':      'Il tuo nome',
        'sub.email.ph':     'Il tuo indirizzo email',
        'sub.chk1':         'Offerte e promozioni',
        'sub.chk2':         'Nuovi articoli',
        'sub.chk3':         'Drops ricondizionati',
        'sub.btn':          'ISCRIVIMI ORA',
        'sub.disclaimer':   "Iscrivendoti accetti di ricevere email da FINSTATECH. Puoi annullare l'iscrizione in qualsiasi momento.",
        'sub.stat1':        'abbonati attivi',
        'sub.stat2':        'email alla settimana',
        'sub.stat3':        'spam. garantito.',
        'sub.success':      '✓ ISCRITTO',
    },

    ko: {
        'nav.menu':      '메뉴',
        'nav.home':      '홈',
        'nav.contact':   '연락처',
        'nav.products':  '제품',
        'nav.subscribe': '구독하기',

        'ft.nav':        '내비게이션',
        'ft.cats':       '카테고리',
        'ft.contact':    '연락처',
        'ft.gaming':     '게이밍 PC',
        'ft.components': '부품',
        'ft.peripherals':'주변기기',
        'ft.refurb':     '리퍼브',
        'ft.send':       '메시지 보내기',
        'ft.hours':      '월 – 금, 오전 9시 – 오후 6시',
        'ft.copy':       '© 2026 FINSTATECH. 모든 권리 보유.',
        'ft.built':      '기술에 대한 열정으로 만들었습니다.',

        'top.picks':  '추천 제품',
        'top.ram.h':  '고속 DDR5 RAM',
        'top.ram.p':  '차세대 성능을 경험하세요.',
        'top.ssd.h':  'Gen4 NVMe SSD',
        'top.ssd.p':  '초고속 로딩 시간을 경험하세요.',
        'top.kb.h':   'RGB 기계식 키보드',
        'top.kb.p':   '클릭감, 반응성, 완전한 커스터마이징.',

        'ref.eyebrow':  '공식 리퍼브 인증',
        'ref.title':    '리퍼브 <span>특가</span>',
        'ref.sub':      '반값. 동일한 성능. 리퍼브 & 검증 완료.',
        'ref.badge':    '50% 할인',
        'ref.mx3s.p':   '무선 마우스, 리퍼브. 어떤 표면에서도 작동.',
        'ref.mxk.p':    '풀사이즈 무선 키보드. 조용하고 백라이트 있음.',
        'ref.cam.p':    '1080p 60fps 웹캠. USB-C, 재택근무 또는 스트리밍에 적합.',
        'ref.zone.p':   '소음 제거 마이크가 있는 오피스 헤드셋. 하루 종일 편안함.',
        'ref.mxa.p':    '소형 여행용 마우스. 유리 위에서도 작동.',
        'ref.mxkm.p':   '소형 무선 키보드. 조용하고 백라이트, 휴대 가능.',

        'prod.gaming':       '<span>게이밍</span> PC',
        'prod.performance':  '<span>퍼포먼스</span> 부품',
        'prod.essential':    '<span>필수</span> 주변기기',
        'prod.view':         '자세히 보기',
        'prod.ryzen.p':      '게이밍 CPU의 왕.',
        'prod.rtx.p':        '1080p/1440p 게이밍에 최고의 가성비.',
        'prod.crucial.p':    '초고속 Gen4 NVMe 스토리지.',
        'prod.gskill.p':     '최적 성능을 위한 6000MHz CL30 DDR5.',
        'prod.glide.p':      '가볍고 인체공학적이며 정밀한.',
        'prod.pad.p':        '최대 커버리지를 위한 XL 마우스패드.',
        'prod.sound.p':      '몰입형 게이밍을 위한 맑은 사운드.',
        'prod.keycaps.p':    '내구성을 위한 PBT 이중 사출 키캡.',

        'pd.back':       '← 제품으로 돌아가기',
        'pd.addcart':    '장바구니에 추가',
        'pd.buy':        '지금 구매',
        'pd.notify':     '✓ 재고 시 알려드리겠습니다',
        'pd.share':      '공유',
        'pd.specs':      '사양',
        'pd.related':    '이런 제품도 좋아하실 수 있어요',

        'cart.title':    '장바구니',
        'cart.empty':    '장바구니가 비어 있습니다.',
        'cart.browse':   '제품 보기 →',
        'cart.remove':   '삭제',
        'cart.subtotal': '소계',
        'cart.shipping': '배송',
        'cart.free':     '무료',
        'cart.total':    '합계',
        'cart.checkout': '결제하기',
        'cart.added':    '✓ 장바구니에 추가됨',
        'cart.demo':     '이것은 데모 스토어입니다. 실제 구매는 이루어지지 않습니다.',

        'ct.eyebrow':    '여기 있습니다',
        'ct.title':      '저희와 <span>연락하세요</span>',
        'ct.desc':       '주문, 제품에 대한 질문이나 인사를 남기고 싶으신가요? 메시지를 보내주시면 곧 답변드리겠습니다.',
        'ct.email.lbl':  '이메일',
        'ct.hours.lbl':  '운영시간',
        'ct.hours.val':  '월 – 금, 오전 9시 – 오후 6시',
        'ct.name.ph':    '이름',
        'ct.email.ph':   '이메일 주소',
        'ct.subject.ph': '제목',
        'ct.msg.ph':     '메시지를 입력하세요...',
        'ct.send':       '메시지 보내기',

        'sub.eyebrow':      '무료 멤버십',
        'sub.hero.title':   '독점 <span>액세스</span>.<br>누구보다 먼저.',
        'sub.hero.desc':    '드롭, 리퍼브 할인, 신제품 출시를 가장 먼저 알아보세요. 스팸 없는 테크 커뮤니티.',
        'sub.perks.title':  '무엇을 얻나요?',
        'sub.p1.h':         '독점 딜',
        'sub.p1.p':         '공개 전 신제품 및 리퍼브 제품 할인에 대한 조기 접근.',
        'sub.p2.h':         '가이드 & 리뷰',
        'sub.p2.p':         '불필요한 내용 없는 기술 콘텐츠 — 비교, 추천 빌드 등.',
        'sub.p3.h':         '리퍼브 드롭',
        'sub.p3.p':         '리퍼브 재고가 소진되기 전에 알려드립니다.',
        'sub.p4.h':         '스팸 없음. 절대로.',
        'sub.p4.p':         '읽을 가치 있는 이메일만. 언제든지 취소 가능.',
        'sub.form.title':   '지금 가입하기',
        'sub.form.sub':     '무료입니다. 항상 그럴 것입니다.',
        'sub.name.ph':      '이름',
        'sub.email.ph':     '이메일 주소',
        'sub.chk1':         '딜 & 할인',
        'sub.chk2':         '새 기사',
        'sub.chk3':         '리퍼브 드롭',
        'sub.btn':          '지금 구독하기',
        'sub.disclaimer':   'FINSTATECH 이메일 수신에 동의합니다. 언제든지 구독을 취소할 수 있습니다.',
        'sub.stat1':        '활성 구독자',
        'sub.stat2':        '주당 이메일',
        'sub.stat3':        '스팸. 보장.',
        'sub.success':      '✓ 구독완료',
    }
};

// ─── Core ────────────────────────────────────────────────────────────────────

let currentLang = localStorage.getItem('finstaLang') || 'en';

function applyLang(lang) {
    const t = translations[lang];
    if (!t) return;
    currentLang = lang;
    localStorage.setItem('finstaLang', lang);
    window.LANG = t;

    document.querySelectorAll('[data-i18n]').forEach(el => {
        const v = t[el.getAttribute('data-i18n')];
        if (v !== undefined) el.textContent = v;
    });

    document.querySelectorAll('[data-i18n-html]').forEach(el => {
        const v = t[el.getAttribute('data-i18n-html')];
        if (v !== undefined) el.innerHTML = v;
    });

    document.querySelectorAll('[data-i18n-ph]').forEach(el => {
        const v = t[el.getAttribute('data-i18n-ph')];
        if (v !== undefined) el.placeholder = v;
    });

    const cur = document.getElementById('langCurrent');
    if (cur) cur.textContent = lang.toUpperCase();
    document.querySelectorAll('.lang-dropdown-menu button[data-lang]').forEach(btn => {
        btn.classList.toggle('active', btn.getAttribute('data-lang') === lang);
    });

    document.documentElement.lang = lang;
}

function toggleLang() {
    document.getElementById('langMenu').classList.toggle('open');
}

function setLang(lang) {
    applyLang(lang);
    document.getElementById('langMenu').classList.remove('open');
}

document.addEventListener('click', function (e) {
    const sw = document.querySelector('.lang-switcher');
    if (sw && !sw.contains(e.target)) {
        const m = document.getElementById('langMenu');
        if (m) m.classList.remove('open');
    }
});

document.addEventListener('DOMContentLoaded', () => {
    applyLang(currentLang);

    const menuLabel = document.querySelector('.menu-label');
    if (menuLabel) {
        menuLabel.addEventListener('click', (e) => {
            if (e.target.closest('.hamburger-dropdown')) return;
            menuLabel.classList.toggle('menu-open');
        });
        document.addEventListener('click', (e) => {
            if (!menuLabel.contains(e.target)) {
                menuLabel.classList.remove('menu-open');
            }
        });
    }
});
